version: 1.2

service:
   subclass: NOT_APPLICABLE
   files:
     - README.md
   scripts:
     start: README.md

workflows:

   -  name:
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

   -  name: workflowB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

tools:

   -  name: toolA
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json

   -  name: toolB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json
