version: 1.2

workflows:

   -  name: foo
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

   -  name: workflowB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

tools:

   -  name: toolA
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json

   -  name: toolB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json

notebooks:

   -  name: foo
      publish: true
      path: /notebook.ipynb
      
   -  name: notebookB
      publish: true
      path: /notebook.ipynb
