version: 1.2

workflows:

   -  name: workflowA
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

   -  name: workflowB
      publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

tools:

   -  name: foo
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json

   -  name: foo
      publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json
