version: 1.2

workflows:

   -  publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

   -  publish: true
      subclass: CWL
      primaryDescriptorPath: /workflow.cwl
      testParameterFiles:
        - /empty.json

tools:

   -  publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json

   -  publish: true
      subclass: CWL
      primaryDescriptorPath: /tool.cwl
      testParameterFiles:
        - /empty.json
